### ISSUE TITLE
Carrying through types to returned output of query

### ISSUE THREAD

**Issue by geelen** [timkendall/tql#97]
First off, can I say THANK YOU for starting this project. I have spent most of the afternoon googling around and chatting to a knowledgeable friend, who didn't know about this either. It wasn't until I started my own version and chose the name `tql`, then searched for _that_ on NPM, that I found this. But it's exactly what I was hoping for!

Atm I'm writing a new graphql server and testing it with a little helper like so:

```ts
await testGraphql(
  `
    query {
      getUserByUsername(username: "glen") {
        id
        posts {
          id
        }
      }
    }
  `,
  {
    getUserById: {
      id: 'user-1234',
      posts: [{ id: 'post-1' }, { id: 'post-2' }, { id: 'post-33' }],
    },
  }
)
```

All it's doing is sending that query string across the wire, parsing the response, and comparing. Super simple.

I was able to drop `tql` straight in to give me a typesafe version of the _query_:

```ts
await testGraphql(
    query('', (t) => [
      t.getUserByUsername({ username: 'glen' }, (t) => [
        t.id(),
        t.posts((t) => [t.id()]),
      ]),
    ]),
  {
    getUserById: {
      id: 'user-1234',
      posts: [{ id: 'post-1' }, { id: 'post-2' }, { id: 'post-33' }],
    },
  }
)
```

And 😍 love it already, much prefer writing TS to GraphQL, didn't love the `(t) =>` at first but returning arrays at each point is a nice touch and it feels fine once you've written a couple...

Question I have is, can I type the return value of my `testGraphql` helper?

Previously I had:

```ts
export async function testGraphql(
  queryStr: string,
  expectedData: any
) {
  // execute queryStr and compare to expectedData
```

Since I was just passing in a string, I couldn't do anything. But now I have:

```ts
export async function testGraphql<T extends Array<Selection>>(
  query: Operation<SelectionSet<T>>,
  expectedData: any
) {
  const queryStr = query.toString()
  // execute queryStr and compare to expectedData
```

That `expectedData` I want to constrain to use the same fields and nesting as the query, but I lack the TS knowledge to reflect across the types to make it happen.

In real-world usage whatever library you use is going to do this reflection for you, I guess (based off [TypedDocumentNode](https://github.com/dotansimha/graphql-typed-document-node), maybe?), but I was wondering if there's a magic TS incantation to make it work here too...

Thanks!

**Comment by timkendall** [comment]
Hey @geelen, thanks for note! 

Not super ergonomic but something like this should work (with pre-1.x releases):

```typescript
import { Result } from '@timkendall/tql'

import { IQuery } from './generated'

export async function testGraphql<T extends Array<Selection>>(
  query: Operation<SelectionSet<T>>,
  expectedData: Result<IQuery, T>,
) {
  const queryStr = query.toString()
  // execute queryStr and compare to expectedData

```

You could make separate `testQuery`, `testMutation`, and `testSubscription` helpers that supply the appropriate first type argument to [`Result`](https://github.com/timkendall/tql/blob/v0.8.0/src/Result.ts#L20).

**Comment by geelen** [comment]
Awesome! Had to tweak `expectedData` to be `expectedData: Result<IQuery, SelectionSet<T>>` but it worked!

> something like this should work (with pre-1.x releases):

I see on npm you've got `1.0.0-rc.5` under the `beta` tag, should I be using that instead of `0.8.0`?

**Comment by timkendall** [comment]
Ah oops nice catch :) Glad you got it working.

> I see on npm you've got 1.0.0-rc.5 under the beta tag, should I be using that instead of 0.8.0?

If the current version is working for your use-cases right now I wouldn’t switch quite yet. That being said if you need TypedDocumentNode support (for use with Apollo client 3 for example) or type-safe variables the give the beta a try. As a heads up, it does tweak the API slightly (can check out the minimal docs at tql.dev).
